# Generated by Django 4.1.4 on 2023-01-04 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0002_category_tb'),
        ('seller', '0002_register_seller_tb_delete_register_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('image', models.FileField(upload_to='')),
                ('details', models.CharField(max_length=20)),
                ('stock', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.category_tb')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.register_seller_tb')),
            ],
        ),
    ]
