# Generated by Django 4.1.4 on 2023-01-08 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_product_tb'),
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Shipping_address', models.CharField(max_length=20)),
                ('Phone', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('Total_price', models.IntegerField()),
                ('Buyerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.register_tb')),
                ('Productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product_tb')),
            ],
        ),
    ]
