# Generated by Django 4.1.4 on 2023-01-04 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0002_category_tb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_tb',
            old_name='Items',
            new_name='category',
        ),
    ]
