# Generated by Django 4.1.4 on 2023-01-04 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0003_rename_items_category_tb_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_tb',
            old_name='category',
            new_name='items',
        ),
    ]
